name: Build KurdApp
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Theos
        uses: theos/setup-theos@v1
        with:
          version: 'master'

      - name: Build Project
        run: |
          make package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KurdApp-Final-Dylib
          path: .theos/obj/*.dylib
